tflite_reader: Fix module load exception with np_utils
This submodule has been removed in recent Keras versions.
For example with keras / tensorflow 2.14 this causes an exception.
It was even unused in the file, so just removing the import fixes it.

Fixes exceptions of form

    File "tflite2tmdl.py", line 24, in <module>
      from tflite_reader import read_tflite
    File "tools/tflite_reader.py", line 25, in <module>
      from keras.utils import np_utils
    ImportError: cannot import name 'np_utils' from 'keras.utils' (venv/lib/python3.11/site-packages/keras/utils/__init__.py)